name: مرحبانية
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ^3.7.2

dependency_overrides:
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  js: ^0.7.1
  uuid: ^4.5.1

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  # cashfree_pg: ^2.0.10+30
  colorlizer: ^0.0.4
  connectivity_plus: 
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  dio: ^5.7.0
  expandable: ^5.0.1
  file_picker: 
  file:
  firebase_core:
  firebase_messaging:
  flutter_date_pickers: ^0.4.3
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.1
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  flutter_stripe: ^11.2.0
  flutter_svg: ^2.0.11
  flutter_widget_from_html: ^0.15.2
  fluttertoast: ^8.2.12
  flutterzilla_fixed_grid: ^0.0.4
  google_sign_in: ^6.2.1
  http_auth: ^1.0.1
  http: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  line_awesome_flutter: ^3.0.1
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  pin_code_fields: ^7.4.0
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  pusher_beams:
    git:
      url: https://github.com/KamrulIbnZaman/pusher-beams-notifications-flutter
      path: packages/pusher_beams
      ref: master
  pusher_channels_flutter:
    git:
      url: https://github.com/KamrulIbnZaman/pusher-channels-flutter
      ref: master
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.0.2+1
  step_progress_indicator: ^1.0.2
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.3.1
  uuid: ^3.0.6
  webview_flutter: ^4.9.0
  youtube_player_flutter: ^9.1.1
  flutter_local_notifications: ^18.0.0
  google_maps_flutter: ^2.3.1
  geolocator: ^13.0.3
  sign_in_with_apple: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/payment/
    - assets/svg/
